# Generated by Django 4.0.4 on 2022-06-03 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceview_api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('age', models.IntegerField()),
                ('sex', models.CharField(choices=[('1', 'male'), ('2', 'female')], default='1', max_length=9)),
            ],
        ),
    ]
