# Generated by Django 4.0.4 on 2022-06-03 20:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceview_api', '0004_alter_options_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='options',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='spaceview_api.user'),
        ),
    ]
