# Generated by Django 4.0.4 on 2022-06-03 20:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceview_api', '0005_options_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='choice_text',
            field=models.CharField(max_length=50),
        ),
        migrations.RemoveField(
            model_name='options',
            name='user',
        ),
        migrations.AddField(
            model_name='options',
            name='user',
            field=models.ManyToManyField(blank=True, null=True, to='spaceview_api.user'),
        ),
    ]
