# Generated by Django 4.0.4 on 2022-06-03 20:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceview_api', '0006_alter_options_choice_text_remove_options_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='user',
            field=models.ManyToManyField(to='spaceview_api.user'),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
