# Generated by Django 4.0.4 on 2022-06-03 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spaceview_api', '0007_alter_options_user_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='user',
            field=models.ManyToManyField(null=True, to='spaceview_api.user'),
        ),
    ]
