# Generated by Django 4.0.5 on 2022-06-09 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('spaceview_api', '0008_alter_options_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='options',
            name='question',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='spaceview_api.question'),
        ),
        migrations.AlterField(
            model_name='options',
            name='user',
            field=models.ManyToManyField(blank=True, to='spaceview_api.user'),
        ),
    ]
